### ISSUE TITLE
Promise based api

### ISSUE THREAD

**Issue by rt2zz** [pellejacobs/redux-persist-node-storage#3]
redux-persist just switched to requiring promise based storage in v5.0.0-beta.13

Unfortunately it is going to be a pain to get everyone updated. Technically the storage can support both (like AsyncStorage and localforage) but since this module is specific to redux-persist may was well just go 100% promises and make the peer dep be redux-persist@5

**Comment by pellejacobs** [comment]
Great! I'm currently very busy, but I always accept PRs. It should not be too hard. Otherwise, I'll have a look this weekend.

**Comment by rt2zz** [comment]
cool, since the underlying implementation here is sync, im thinking this can be as easy as adding some `return Promise.resolve(value` and `return Promise.reject(err)` calls. I suppose the open question is, should the lib support *both* promise and callback (thus backwards compat with older redux-persist versions) or should it move forward promise only and enforce via peer deps?

Ill probably take a longer look this weekend.

**Comment by junactl** [comment]
Whats missing for publishing a new version of the npm?
