### ISSUE TITLE
Is reading and writing "fully" asynchronous?

### ISSUE THREAD

**Issue by nessup** [pellejacobs/redux-persist-node-storage#5]
From my reading of the code, it seems like it's not. For example, in [index.ts](https://github.com/pellejacobs/redux-persist-node-storage/blob/6afabacfdf1ea9e786db5308c3d7f637c05a289f/src/index.ts#L10-L19)

```ts
  getItem (key: string) {
    return new Promise<string>((resolve, reject) => {
      try {
        const storedValue = this.localStorage.getItem(key)
        process.nextTick(() => resolve(storedValue))
      } catch (e) {
        reject(e)
      }
    })
  }
```

`localStorage.getItem()` is called in the body of the resolver function, which the MDN says [is executed immediately](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Syntax). I believe this means the calling thread is blocked by `localStorage.getItem()`. I understand all "asynchronous" code blocks the calling thread to some extent, but it might be helpful to clarify somewhere that reading/writing is using the blocking sync API.

Thank you for writing this project, and thank you for your time!

**Comment by pellejacobs** [comment]
As you mentioned, all localStorage calls are synchronous and the node implementation is not any different. If you want, feel free to open a PR to update the readme.
