### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined when importing in NativeScript

### ISSUE THREAD

**Issue by tafelnl** [pellejacobs/redux-persist-node-storage#6]
If I import the library (in **NativeScript**) like it says in the docs: `import { AsyncNodeStorage } from 'redux-persist-node-storage'`
I get the following error: `TypeError: Cannot read property 'slice' of undefined when importing`

**UPDATE:**
This is because of how the NativeScript environment is setup, read my comment below for explanation

**Comment by pellejacobs** [comment]
Interesting. We're not using `slice` anywhere in the codebase, maybe it's a dependency that's causing the issue.
Could you provide a bit more context, and potentially a small example that replicates the issue?

**Comment by tafelnl** [comment]
I was using this library in NativeScript. I am still a rookie in working with NativeScript, hence I was not aware that it is not a 'normal' Node.js environment and therefore some npm packages won't work as expected. (see also https://github.com/EddyVerbruggen/nativescript-nodeify)

The error was therefore indeed caused by a dependency.
More specifically in the 
`node_modules/readable-stream/lib/_stream_writable.js`
file the following line caused the error 
`var asyncWrite = !process.browser && ['v0.10', 'v0.9.'].indexOf(process.version.slice(0, 5)) > -1 ? setImmediate : pna.nextTick;`
Since `process.version` is undefined in a NativeScript environment. This could be fixed by setting `process.version` manually. But that will just postpone the problem. Because sometime somewhere another dependency will rely on anything that is Node.js specific.

**So the solution:**
_Don't use this library with NativeScript_. Just use a (simple key-value) document oriented database[1] (like https://www.npmjs.com/package/snap-db for example) or the built-in NativeScript storage which makes use of application settings (https://docs.nativescript.org/ns-framework-modules/application-settings)
The only thing you then have to do to be able to use it with redux, is writing a simple adapter that implements the following methods:
`getItem(key)`
`setItem(key, value)`
`removeItem(key)`

as stated in the readme of redux-perist:

> custom any conforming storage api implementing the following methods: setItem getItem removeItem. (NB: These methods must support promises)

(https://github.com/rt2zz/redux-persist#storage-engines)

You can take this file as an example of such an adapter: https://github.com/pellejacobs/redux-persist-node-storage/blob/master/src/index.ts

_[1] You can use anything really, just as long as it does not depend on any Node.js specific methods etc. (so a zero-dependency library will do for example)_
