### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by amyblais** [pellejacobs/redux-persist-node-storage#7]
@pellejacobs Thanks for sharing this project! We have added your library in the Mattermost redux https://github.com/mattermost/mattermost-redux/blob/master/package.json#L37.

Would you consider adding the MIT license as a LICENSE file?

If you use a license it would make it easy to add your work to other open source projects, and we'd love to keep your work in ours.

Thanks kindly for your consideration and let me know if you have any questions!

Please see more context here: https://github.com/mattermost/mattermost-redux/pull/1179#pullrequestreview-437729012.

**Comment by pellejacobs** [comment]
Of course: 7dc33678c20885781d0c96002f569bc0d448a5ea
